/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.bernard_flo.spring.yamltoproperties

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
}
